Heartrate:
    type: object
    config:
        fields:
            id:
                type: "ID!"
            bpm:
                type: "Int!"
                description: "Beats per minute"
            date: 
                type: "String"
                description: "When the heartrate was measured"
                